print("Please enter the following:")
print('')
adjective = input("adjective: ")
animal = input("animal: ")
verb1 = input("verb: ")
exclamation = input("exclamation: ")
verb2 = input("verb: ")
verb3 = input("verb: ")
pet = input("pet: ")
verb4 = input('verb: ')
location = input('location: ')

print('')
print('Your story is:')
print('')
print("The other day, I was really in trouble. It all started when I saw a very")
print(adjective.lower(), animal.lower(), verb1.lower(), 'down the hallway.', '"' + exclamation.capitalize() + '!"', 'I yelled. But all')
print('I could think to do was to', verb2.lower(), 'over and over. Miraculously,')
print('that caused it to stop, but not before it tried to', verb3.lower())
print('right in front of my family. After it stopped, my pet', pet.lower(), 'started to')
print(verb4.lower(), 'until the', animal.lower(), 'got scared and ran all the way to', location.capitalize() +'.')